language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew test
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)